import type { Idea } from './types';
import {
  Category,
  StatusPrimitive,
  BuilderProfile,
  Difficulty,
  UserSegment,
  DomainExpertise,
  CapitalReq,
  SecurityCriticality,
  OpsBurden,
} from './types';

export const ideas: Idea[] = [
  // ── Karma ──────────────────────────────────────────────
  {
    id: 'karma-gated-access',
    title: 'Karma-Gated Content Feed',
    category: Category.reputation,
    superpowers: [StatusPrimitive.karma],
    builderProfiles: [BuilderProfile.frontendDev],
    what: 'A social feed where creators publish posts visible only to followers who meet a minimum Karma tier — think Substack meets on-chain reputation.',
    whyStatus: 'Karma tiers are resolved on-chain, so access control is trustless — no subscription billing, no platform lock-in, and Sybil-resistant by design.',
    mvp: 'Feed with public + gated posts, tier-check middleware (possibly on-chain), creator dashboard showing audience breakdown by Karma tier.',
    difficulty: Difficulty.lowMed,
    userSegment: UserSegment.communityCreator,
    domainExpertise: DomainExpertise.communityDesign,
    capitalRequirement: CapitalReq.none,
    securityCriticality: SecurityCriticality.medium,
    opsBurden: OpsBurden.low,
  },
  {
    id: 'karma-liquidity-protocol',
    title: 'Karma-Boosted Yield Vault',
    category: Category.reputation,
    superpowers: [StatusPrimitive.karma],
    builderProfiles: [BuilderProfile.contractDev],
    what: 'A DeFi vault where depositors with higher Karma tiers receive boosted APY — early supporters and active participants earn better returns.',
    whyStatus: 'The native reputation graph lets the vault weight rewards by proven participation instead of token-weighted voting or off-chain allowlists.',
    mvp: 'Single-asset vault with two yield tiers, on-chain Karma tier lookup at deposit, and a dashboard showing effective APY per tier.',
    difficulty: Difficulty.medHigh,
    userSegment: UserSegment.traderDefi,
    domainExpertise: DomainExpertise.defiMechanisms,
    capitalRequirement: CapitalReq.seedLiquidity,
    securityCriticality: SecurityCriticality.high,
    opsBurden: OpsBurden.medium,
  },
  {
    id: 'karma-incentive-market',
    title: 'Karma Bounty Board',
    category: Category.reputation,
    superpowers: [StatusPrimitive.karma],
    builderProfiles: [BuilderProfile.fullStack],
    what: 'A bounty marketplace where only users above a Karma threshold can claim tasks — project teams post work (bug reports, translations, onboarding guides) and pay verified contributors.',
    whyStatus: 'Karma-gating filters out spamming bots and low-effort submissions, giving bounty issuers confidence that claimants have a real track record on the network.',
    mvp: 'Bounty listing page, Karma-gated claim flow, submission review panel, and on-chain payout on approval.',
    difficulty: Difficulty.med,
    userSegment: UserSegment.communityCreator,
    domainExpertise: DomainExpertise.communityDesign,
    capitalRequirement: CapitalReq.operatingTreasury,
    securityCriticality: SecurityCriticality.medium,
    opsBurden: OpsBurden.medium,
  },
  {
    id: 'karma-dynamic-pricing',
    title: 'Karma-Tiered NFT Marketplace',
    category: Category.reputation,
    superpowers: [StatusPrimitive.karma],
    builderProfiles: [BuilderProfile.frontendDev],
    what: 'An NFT marketplace where listing fees, royalties, and early-access windows adjust based on the buyer\'s and seller\'s Karma tier — trusted participants get better terms automatically.',
    whyStatus: 'On-chain tier resolution at checkout means dynamic pricing is enforced trustlessly — no coupon codes, no backend allowlists.',
    mvp: 'NFT listing + purchase flow with tiered fee schedule, on-chain tier check at checkout, and seller analytics showing sales by buyer tier.',
    difficulty: Difficulty.lowMed,
    userSegment: UserSegment.communityCreator,
    domainExpertise: DomainExpertise.consumerProduct,
    capitalRequirement: CapitalReq.none,
    securityCriticality: SecurityCriticality.medium,
    opsBurden: OpsBurden.low,
  },

  // ── Privacy ───────────────────────────────────────────
  {
    id: 'stealth-address-payments',
    title: 'Stealth Address Payments',
    category: Category.privacy,
    superpowers: [StatusPrimitive.privacy, StatusPrimitive.gasless],
    builderProfiles: [BuilderProfile.protocolDev],
    what: 'One-time receiving addresses with unlinkable spend paths.',
    whyStatus: 'Privacy primitives + low-friction transaction UX.',
    mvp: 'Address generation, receive flow, and private spend flow.',
    difficulty: Difficulty.medHigh,
    userSegment: UserSegment.consumer,
    domainExpertise: DomainExpertise.privacy,
    capitalRequirement: CapitalReq.none,
    securityCriticality: SecurityCriticality.critical,
    opsBurden: OpsBurden.low,
  },
  {
    id: 'private-payroll',
    title: 'Private Payroll & Savings',
    category: Category.privacy,
    superpowers: [StatusPrimitive.privacy],
    builderProfiles: [BuilderProfile.fullStack],
    what: 'Salary and savings rails that do not expose balances and recipients.',
    whyStatus: 'Real-world demand where public ledgers fail expectations.',
    mvp: 'Employer payout batch + recipient claim + shielded vault.',
    difficulty: Difficulty.med,
    userSegment: UserSegment.daoOrgOps,
    domainExpertise: DomainExpertise.paymentsFinops,
    capitalRequirement: CapitalReq.operatingTreasury,
    securityCriticality: SecurityCriticality.high,
    opsBurden: OpsBurden.medium,
  },
  {
    id: 'shielded-microtransactions',
    title: 'Shielded Microtransactions / Card Layer',
    category: Category.privacy,
    superpowers: [StatusPrimitive.privacy, StatusPrimitive.gasless],
    builderProfiles: [BuilderProfile.fullStack],
    what: 'Low-value payments and subscriptions with hidden amounts/participants.',
    whyStatus: 'Gasless interactions make frequent payments viable.',
    mvp: 'Private tip/subscription flow with recurring authorization.',
    difficulty: Difficulty.medHigh,
    userSegment: UserSegment.consumer,
    domainExpertise: DomainExpertise.paymentsFinops,
    capitalRequirement: CapitalReq.operatingTreasury,
    securityCriticality: SecurityCriticality.high,
    opsBurden: OpsBurden.medium,
  },
  {
    id: 'private-lending',
    title: 'Private Lending & Borrowing',
    category: Category.privacy,
    superpowers: [StatusPrimitive.privacy, StatusPrimitive.karma],
    builderProfiles: [BuilderProfile.contractDev, BuilderProfile.protocolDev],
    what: 'Borrow/lend flows that avoid public position leakage.',
    whyStatus: 'Privacy + Karma-based trust signals.',
    mvp: 'One collateral type, one borrow asset, private health checks.',
    difficulty: Difficulty.high,
    userSegment: UserSegment.traderDefi,
    domainExpertise: DomainExpertise.defiMechanisms,
    capitalRequirement: CapitalReq.deepLiquidity,
    securityCriticality: SecurityCriticality.critical,
    opsBurden: OpsBurden.high,
  },
  {
    id: 'private-multisig',
    title: 'Private Multisig',
    category: Category.privacy,
    superpowers: [StatusPrimitive.privacy],
    builderProfiles: [BuilderProfile.contractDev, BuilderProfile.protocolDev],
    what: 'Multisig ops where signers, threshold, and tx details are obscured.',
    whyStatus: 'Privacy-sensitive orgs can still operate on-chain.',
    mvp: 'Policy setup + signing flow + execution log with selective disclosure.',
    difficulty: Difficulty.high,
    userSegment: UserSegment.daoOrgOps,
    domainExpertise: DomainExpertise.privacy,
    capitalRequirement: CapitalReq.none,
    securityCriticality: SecurityCriticality.critical,
    opsBurden: OpsBurden.medium,
  },

  // ── Social ─────────────────────────────────────────────
  {
    id: 'social-mini-app',
    title: 'Gasless Micro-Blogging Platform',
    category: Category.social,
    superpowers: [StatusPrimitive.karma, StatusPrimitive.gasless],
    builderProfiles: [BuilderProfile.frontendDev],
    what: 'A Twitter-style micro-blog where every post, reply, and like is an on-chain action that costs the user nothing — with Karma badges that surface trusted voices.',
    whyStatus: 'Gasless transactions make post-per-action economics viable; Karma badges replace arbitrary blue-check systems with reputation earned through actual network participation.',
    mvp: 'Timeline feed, post/reply/like actions, user profiles with Karma trust badges, and basic content moderation controls.',
    difficulty: Difficulty.lowMed,
    userSegment: UserSegment.consumer,
    domainExpertise: DomainExpertise.consumerProduct,
    capitalRequirement: CapitalReq.none,
    securityCriticality: SecurityCriticality.low,
    opsBurden: OpsBurden.medium,
  },
  {
    id: 'creator-economy-toolkit',
    title: 'Fan Pass Platform',
    category: Category.social,
    superpowers: [StatusPrimitive.gasless],
    builderProfiles: [BuilderProfile.frontendDev],
    what: 'A platform where creators mint free digital passes that unlock exclusive content, group chats, and IRL event access — fans collect passes gaslessly.',
    whyStatus: 'Zero-cost minting and claiming removes the paywall friction from community passes, letting creators grow audiences without asking fans to pay gas.',
    mvp: 'Creator page with pass minting, fan claim flow, pass-gated content section, and event check-in via pass verification.',
    difficulty: Difficulty.med,
    userSegment: UserSegment.communityCreator,
    domainExpertise: DomainExpertise.consumerProduct,
    capitalRequirement: CapitalReq.none,
    securityCriticality: SecurityCriticality.medium,
    opsBurden: OpsBurden.medium,
  },
  {
    id: 'community-governance',
    title: 'DAO Proposal & Karma-Weighted Voting App',
    category: Category.social,
    superpowers: [StatusPrimitive.karma, StatusPrimitive.gasless],
    builderProfiles: [BuilderProfile.fullStack],
    what: 'A governance app where community members submit proposals and vote with weight proportional to their Karma tier — active contributors have a louder voice than passive holders.',
    whyStatus: 'Karma-weighted voting rewards real participation over token accumulation, and gasless voting removes the cost barrier that suppresses turnout in most DAOs.',
    mvp: 'Proposal submission form, Karma-weighted voting with on-chain tallying, results dashboard with participation breakdown by tier.',
    difficulty: Difficulty.med,
    userSegment: UserSegment.daoOrgOps,
    domainExpertise: DomainExpertise.communityDesign,
    capitalRequirement: CapitalReq.none,
    securityCriticality: SecurityCriticality.medium,
    opsBurden: OpsBurden.low,
  },

  // ── Games ──────────────────────────────────────────────
  {
    id: 'onchain-strategy-game',
    title: 'Fog-of-War Conquest Game',
    category: Category.games,
    superpowers: [StatusPrimitive.privacy, StatusPrimitive.gasless],
    builderProfiles: [BuilderProfile.fullStack],
    what: 'A hex-grid territory control game where troop positions are hidden via private state and every move is a gasless on-chain transaction — think Risk board game with real fog of war on-chain.',
    whyStatus: 'Privacy primitives enable genuine hidden information (not just client-side fog), while gasless moves make the rapid back-and-forth of strategy games economically feasible.',
    mvp: 'Hex map with fog-of-war, one unit type, private troop placement, turn resolution, and a match leaderboard.',
    difficulty: Difficulty.medHigh,
    userSegment: UserSegment.consumer,
    domainExpertise: DomainExpertise.consumerProduct,
    capitalRequirement: CapitalReq.none,
    securityCriticality: SecurityCriticality.medium,
    opsBurden: OpsBurden.medium,
  },
  {
    id: 'prediction-market',
    title: 'Prediction Market',
    category: Category.games,
    superpowers: [StatusPrimitive.privacy, StatusPrimitive.gasless],
    builderProfiles: [BuilderProfile.fullStack],
    what: 'Markets with low-friction entries and private participant positions.',
    whyStatus: 'Better market participation and less copy-trading behavior.',
    mvp: 'Market creation + position entry + settlement + basic analytics.',
    difficulty: Difficulty.medHigh,
    userSegment: UserSegment.traderDefi,
    domainExpertise: DomainExpertise.defiMechanisms,
    capitalRequirement: CapitalReq.seedLiquidity,
    securityCriticality: SecurityCriticality.high,
    opsBurden: OpsBurden.high,
  },

  // ── DeFi ───────────────────────────────────────────────
  {
    id: 'native-dex-companion',
    title: 'Karma-Tiered Swap Router',
    category: Category.defi,
    superpowers: [StatusPrimitive.karma],
    builderProfiles: [BuilderProfile.contractDev],
    what: 'A swap interface that routes trades through the best on-chain pools and gives high-Karma users reduced fees and priority execution — a loyalty program baked into the DEX layer.',
    whyStatus: 'Karma tiers let the router offer fee discounts trustlessly, and tight integration with native liquidity means better rates without external aggregator dependencies.',
    mvp: 'Token swap UI with tiered fee display, Karma-aware routing logic, LP position panel, and trade history showing fees saved by tier.',
    difficulty: Difficulty.med,
    userSegment: UserSegment.traderDefi,
    domainExpertise: DomainExpertise.defiMechanisms,
    capitalRequirement: CapitalReq.seedLiquidity,
    securityCriticality: SecurityCriticality.high,
    opsBurden: OpsBurden.medium,
  },
  {
    id: 'public-funding-interface',
    title: 'Public Funding Interface',
    category: Category.defi,
    superpowers: [StatusPrimitive.karma, StatusPrimitive.gasless],
    builderProfiles: [BuilderProfile.frontendDev],
    what: 'End-to-end grant discovery, proposal, voting, and tracking dashboard.',
    whyStatus: 'Directly supports ecosystem growth flywheel.',
    mvp: 'Proposal board + vote screen + grant progress tracker.',
    difficulty: Difficulty.med,
    userSegment: UserSegment.daoOrgOps,
    domainExpertise: DomainExpertise.communityDesign,
    capitalRequirement: CapitalReq.none,
    securityCriticality: SecurityCriticality.medium,
    opsBurden: OpsBurden.low,
  },
];
